---
title: "Dataprep"
author: "Leonie H."
date: "2023-08-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/admin/Desktop/MPI/Share/ShareSEM/ShareSEM")

library(haven)
library(tidyverse)

## Wave 1: Demographics (demo), Cognitive Function (cf), Mental Health (mf)

demo1 <- read_dta("sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_dn.dta")  ## read data
cf1 <- read_dta("sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_cf.dta")
mh1 <- read_dta("sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_mh.dta")
casp1 <- read_dta("sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_dropoff.dta")

demo1items<- demo1 %>% dplyr::select("mergeid", "dn003_", "dn042_") %>%  ## select items
  rename_at(vars(-mergeid),function(x) paste0(x,"_1"))            ## add wave number as suffix to variable name

cf1items<- cf1 %>% dplyr::select(mergeid, contains ("cf0"))%>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_1"))

mh1items<- mh1 %>% dplyr::select(mergeid, contains ("mh0")) %>%
  dplyr::select(- c( "mh018_", "mh019_", "mh020_", "mh021_")) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_1"))

casp1items <- casp1 %>% dplyr::select("mergeid", "q2_a", "q2_b", "q2_c", "q2_d","q2_e","q2_f","q2_g","q2_h","q2_i",
              "q2_j","q2_k","q2_l") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_1"))


## Wave 2 

demo2 <- read_dta("sharew2_rel8-0-0_ALL_datasets_stata/sharew2_rel8-0-0_dn.dta")  
cf2 <- read_dta("sharew2_rel8-0-0_ALL_datasets_stata/sharew2_rel8-0-0_cf.dta")
mh2 <- read_dta("sharew2_rel8-0-0_ALL_datasets_stata/sharew2_rel8-0-0_mh.dta")
casp2 <- read_dta("sharew2_rel8-0-0_ALL_datasets_stata/sharew2_rel8-0-0_ac.dta")

demo2items<- demo2 %>% dplyr::select("mergeid", "dn003_", "dn042_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_2"))

cf2items<- cf2 %>% dplyr::select(mergeid, contains ("cf0")) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_2"))

mh2items<- mh2 %>% dplyr::select(mergeid, contains ("mh0")) %>%
  dplyr::select (- c ("mh018_", "mh019_", contains ("mh02"))) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_2"))

casp2items<- casp2 %>% dplyr::select("mergeid", "ac014_", "ac015_", "ac016_", "ac017_","ac018_","ac019_","ac020_", "ac021_","ac022_","ac023_","ac024_","ac025_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_2"))

## Wave 3 

#demo3 <- read_dta("")  
#cf3 <- read_dta("")
#mh3 <- read_dta("")
casp3 <- read_dta("sharew3_rel8-0-0_ALL_datasets_stata/sharew3_rel8-0-0_ac.dta")

#demo3items<- demo3 %>% select("mergeid", "dn003_", "dn042_") %>%
#  rename_at(vars(-mergeid),function(x) paste0(x,"3"))

#cf3items<- cf3 %>% select(mergeid, contains ("cf0")) %>%
#  rename_at(vars(-mergeid),function(x) paste0(x,"_3"))

#mh3items<- mh3 %>% select(mergeid, contains ("mh0")) %>%
#  select (- c ("mh018_", "mh019_", contains ("mh02"))) %>%
#  rename_at(vars(-mergeid),function(x) paste0(x,"_3"))

#casp3items<- casp3 %>% dplyr::select("mergeid", "ac014_", "ac015_", "ac016_", "ac017_","ac018_","ac019_","ac020_","ac021_","ac022_","ac023_","ac024_","ac025_") %>%
#  rename_at(vars(-mergeid),function(x) paste0(x,"_3"))


## Wave 4

demo4 <- read_dta("sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_dn.dta")
cf4 <- read_dta("sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_cf.dta")
mh4 <- read_dta("sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_mh.dta")
casp4 <- read_dta("sharew4_rel8-0-0_ALL_datasets_stata/sharew4_rel8-0-0_ac.dta")

demo4items<- demo4 %>% dplyr::select("mergeid", "dn003_", "dn042_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_4"))

cf4items<- cf4 %>% dplyr::select(mergeid, contains ("cf0")) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_4"))

mh4items<- mh4 %>% dplyr::select(mergeid, contains ("mh0")) %>%
  dplyr::select( -c( "mh018_", "mh019_", contains ("mh02"), contains("mh03"))) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_4"))

casp4items<- casp4 %>% dplyr::select("mergeid", "ac014_", "ac015_", "ac016_", "ac017_","ac018_","ac019_","ac020_", "ac021_","ac022_","ac023_","ac024_","ac025_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_4"))
          
## Wave 5

demo5 <- read_dta("sharew5_rel8-0-0_ALL_datasets_stata/sharew5_rel8-0-0_dn.dta")
cf5 <- read_dta("sharew5_rel8-0-0_ALL_datasets_stata/sharew5_rel8-0-0_cf.dta")
mh5 <- read_dta("sharew5_rel8-0-0_ALL_datasets_stata/sharew5_rel8-0-0_mh.dta")
casp5 <- read_dta("sharew5_rel8-0-0_ALL_datasets_stata/sharew5_rel8-0-0_ac.dta")

demo5items<- demo5 %>% dplyr::select("mergeid", "dn003_", "dn042_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_5"))

cf5items<- cf5 %>% dplyr::select(mergeid, contains ("cf0")) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_5"))

mh5items<- mh5 %>% dplyr::select(mergeid, contains ("mh0")) %>%
  dplyr::select( -c(contains ("mh02"), contains("mh03"))) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_5"))

casp5items<- casp5 %>% dplyr::select("mergeid", "ac014_", "ac015_", "ac016_", "ac017_","ac018_","ac019_","ac020_", "ac021_","ac022_","ac023_","ac024_","ac025_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_5"))

## Wave 6

demo6 <- read_dta("sharew6_rel8-0-0_ALL_datasets_stata/sharew6_rel8-0-0_dn.dta")
cf6 <- read_dta("sharew6_rel8-0-0_ALL_datasets_stata/sharew6_rel8-0-0_cf.dta")
mh6 <- read_dta("sharew6_rel8-0-0_ALL_datasets_stata/sharew6_rel8-0-0_mh.dta")
casp6 <- read_dta("sharew6_rel8-0-0_ALL_datasets_stata/sharew6_rel8-0-0_ac.dta")

demo6items<- demo6 %>% dplyr::select("mergeid", "dn003_", "dn042_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_6"))

cf6items<- cf6 %>% dplyr::select(mergeid, contains ("cf0")) %>%
  dplyr::select( -"cf019_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_6"))

mh6items<- mh6 %>% dplyr::select(mergeid, contains ("mh0")) %>%
  dplyr::select( -c(contains ("mh02"), contains("mh03"))) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_6"))

casp6items<- casp6 %>% dplyr::select("mergeid","ac014_", "ac015_", "ac016_", "ac017_","ac018_","ac019_","ac020_",  "ac021_","ac022_","ac023_","ac024_","ac025_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_6"))

## Wave 7

demo7 <- read_dta("sharew7_rel8-0-0_ALL_datasets_stata/sharew7_rel8-0-0_dn.dta")
cf7 <- read_dta("sharew7_rel8-0-0_ALL_datasets_stata/sharew7_rel8-0-0_cf.dta")
mh7 <- read_dta("sharew7_rel8-0-0_ALL_datasets_stata/sharew7_rel8-0-0_mh.dta")
casp7 <- read_dta("sharew7_rel8-0-0_ALL_datasets_stata/sharew7_rel8-0-0_ac.dta")


demo7items<- demo7 %>% dplyr::select("mergeid", "dn003_", "dn042_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_7"))

cf7items<- cf7 %>% dplyr::select(mergeid, contains ("cf0")) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_7"))

mh7items<- mh7 %>% dplyr::select(mergeid, contains ("mh0")) %>%
  dplyr::select( -c(contains ("mh02"), contains("mh03"))) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_7"))

casp7items<- casp7 %>% dplyr::select("mergeid","ac014_", "ac015_", "ac016_", "ac017_","ac018_","ac019_","ac020_", "ac021_","ac022_","ac023_","ac024_","ac025_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_7"))

## Wave 8

demo8 <- read_dta("sharew8_rel8-0-0_ALL_datasets_stata/sharew8_rel8-0-0_dn.dta")
cf8 <- read_dta("sharew8_rel8-0-0_ALL_datasets_stata/sharew8_rel8-0-0_cf.dta")
mh8 <- read_dta("sharew8_rel8-0-0_ALL_datasets_stata/sharew8_rel8-0-0_mh.dta")
casp8 <- read_dta("sharew8_rel8-0-0_ALL_datasets_stata/sharew8_rel8-0-0_ac.dta")

demo8items<- demo8 %>% dplyr::select("mergeid", "dn003_", "dn042_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_8"))

cf8items<- cf8 %>% dplyr::select(mergeid, contains ("cf0")) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_8"))

mh8items<- mh8 %>% dplyr::select(mergeid, contains ("mh0")) %>%
  dplyr::select( -c(contains ("mh02"), contains("mh03"))) %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_8"))

casp8items<- casp8 %>% dplyr::select("mergeid", "ac014_", "ac015_", "ac016_", "ac017_","ac018_","ac019_","ac020_", "ac021_","ac022_","ac023_","ac024_","ac025_") %>%
  rename_at(vars(-mergeid),function(x) paste0(x,"_8"))


## Merge all Data for Cognitive Function including Demographics

cf_all <- full_join(demo1items, cf1items, by = "mergeid") %>%
#  full_join (demo2items, by = "mergeid") %>%
  full_join (cf2items, by = "mergeid") %>%
#  full_join (demo4items, by = "mergeid") %>%
  full_join (cf4items, by = "mergeid") %>%
#  full_join (demo5items, by = "mergeid") %>%
  full_join (cf5items, by = "mergeid") %>%
#  full_join (demo6items, by = "mergeid") %>%
  full_join (cf6items, by = "mergeid") %>%
#  full_join (demo7items, by = "mergeid") %>%
  full_join (cf7items, by = "mergeid") %>%
#  full_join (demo8items, by = "mergeid") %>%
  full_join (cf8items, by = "mergeid")

dim(cf_all)  
names(cf_all)

library(tidyr)

head(cf_all)
cf_long <- pivot_longer(cf_all, cols = -c(1:3), 
             names_to = c('.value', 'wave'), 
             names_pattern = '(.*)(\\d+)')


## Merge all Data for Mental Health including Demographics

mh_all <- full_join(demo1items, mh1items, by = "mergeid") %>%
#  full_join (demo2items, by = "mergeid") %>%
  full_join (mh2items, by = "mergeid") %>%
#  full_join (demo4items, by = "mergeid") %>%
  full_join (mh4items, by = "mergeid") %>%
#  full_join (demo5items, by = "mergeid") %>%
  full_join (mh5items, by = "mergeid") %>%
#  full_join (demo6items, by = "mergeid") %>%
  full_join (mh6items, by = "mergeid") %>%
#  full_join (demo7items, by = "mergeid") %>%
  full_join (mh7items, by = "mergeid") %>%
#  full_join (demo8items, by = "mergeid") %>%
  full_join (mh8items, by = "mergeid")

dim(mh_all)
mh_long <- pivot_longer(mh_all, cols = -c(1:3), 
                        names_to = c('.value', 'wave'), 
                        names_pattern = '(.*)(\\d+)')
head(mh_long)

cfmh_all <- full_join(cf_all, mh_all, by = "mergeid") 
dim(cfmh_all)

cfmh_long <- pivot_longer(cfmh_all, cols = -c(1:3), 
                        names_to = c('.value', 'wave'), 
                        names_pattern = '(.*)(\\d+)')
head(cfmh_long)


## Merge all Data for Casp including Demographics

casp_all <- full_join(demo1items, casp1items, by = "mergeid") %>%
  full_join (casp2items, by = "mergeid") %>%
  #full_join (casp3items, by = "mergeid") %>%
  full_join (casp4items, by = "mergeid") %>%
  full_join (casp5items, by = "mergeid") %>%
  full_join (casp6items, by = "mergeid") %>%
  full_join (casp7items, by = "mergeid") %>%
  full_join (casp8items, by = "mergeid")

dim(casp_all)  
names(casp_all)

library(tidyr)

head(casp_all)
casp_long <- pivot_longer(casp_all, cols = -c(1:3), 
             names_to = c('.value', 'wave'), 
             names_pattern = '(.*)(\\d+)')

#renaming variables

# Read and Prepare Data
```

```{r}
# read
demo <- read_delim("cf_all.csv", delim = ";", 
    escape_double = FALSE, col_types = cols(...1 = col_skip()), 
    trim_ws = TRUE)
casp <- read_delim("casp.csv", delim = ";", 
    escape_double = FALSE, col_types = cols(...1 = col_skip()), 
    trim_ws = TRUE)

```

```{r}
casp <- casp %>% 
  rename(
    # name CASP-12 Items as variables according to factor structure.
    "cC1_1" = "q2_a_1",
    "cC2_1" = "q2_b_1",
    "cC3_1" = "q2_c_1",
    "cA1_1" = "q2_d_1",
    "cA2_1" = "q2_e_1",
    "cA3_1" = "q2_f_1",
    "cP1_1" = "q2_g_1",
    "cP2_1" = "q2_h_1",
    "cP3_1" = "q2_i_1",
    "cS1_1" = "q2_j_1",
    "cS2_1" = "q2_k_1",
    "cS3_1" = "q2_l_1",
    #
    "cC1_2" = "ac014__2",
    "cC2_2" = "ac015__2",
    "cC3_2" = "ac016__2",
    "cA1_2" = "ac017__2",
    "cA2_2" = "ac018__2",
    "cA3_2" = "ac019__2",
    "cP1_2" = "ac020__2",
    "cP2_2" = "ac021__2",
    "cP3_2" = "ac022__2",
    "cS1_2" = "ac023__2",
    "cS2_2" = "ac024__2",
    "cS3_2" = "ac025__2",
    #
    "cC1_4" = "ac014__4",
    "cC2_4" = "ac015__4",
    "cC3_4" = "ac016__4",
    "cA1_4" = "ac017__4",
    "cA2_4" = "ac018__4",
    "cA3_4" = "ac019__4",
    "cP1_4" = "ac020__4",
    "cP2_4" = "ac021__4",
    "cP3_4" = "ac022__4",
    "cS1_4" = "ac023__4",
    "cS2_4" = "ac024__4",
    "cS3_4" = "ac025__4",
    #
    "cC1_5" = "ac014__5",
    "cC2_5" = "ac015__5",
    "cC3_5" = "ac016__5",
    "cA1_5" = "ac017__5",
    "cA2_5" = "ac018__5",
    "cA3_5" = "ac019__5",
    "cP1_5" = "ac020__5",
    "cP2_5" = "ac021__5",
    "cP3_5" = "ac022__5",
    "cS1_5" = "ac023__5",
    "cS2_5" = "ac024__5",
    "cS3_5" = "ac025__5",
    #
    "cC1_6" = "ac014__6",
    "cC2_6" = "ac015__6",
    "cC3_6" = "ac016__6",
    "cA1_6" = "ac017__6",
    "cA2_6" = "ac018__6",
    "cA3_6" = "ac019__6",
    "cP1_6" = "ac020__6",
    "cP2_6" = "ac021__6",
    "cP3_6" = "ac022__6",
    "cS1_6" = "ac023__6",
    "cS2_6" = "ac024__6",
    "cS3_6" = "ac025__6",
    #
    "cC1_7" = "ac014__7",
    "cC2_7" = "ac015__7",
    "cC3_7" = "ac016__7",
    "cA1_7" = "ac017__7",
    "cA2_7" = "ac018__7",
    "cA3_7" = "ac019__7",
    "cP1_7" = "ac020__7",
    "cP2_7" = "ac021__7",
    "cP3_7" = "ac022__7",
    "cS1_7" = "ac023__7",
    "cS2_7" = "ac024__7",
    "cS3_7" = "ac025__7",
    #
    "cC1_8" = "ac014__8",
    "cC2_8" = "ac015__8",
    "cC3_8" = "ac016__8",
    "cA1_8" = "ac017__8",
    "cA2_8" = "ac018__8",
    "cA3_8" = "ac019__8",
    "cP1_8" = "ac020__8",
    "cP2_8" = "ac021__8",
    "cP3_8" = "ac022__8",
    "cS1_8" = "ac023__8",
    "cS2_8" = "ac024__8",
    "cS3_8" = "ac025__8"
  )

View(casp)
```

```{r}
casp <- casp %>% 
        rename(
        "yrbirth" = "dn003__1",
        "gender"  = "dn042__1"
               ) 

```

```{r}
demo <- demo %>% 
        rename(
        "yrbirth" = "dn003__1",
        "gender"  = "dn042__1" 
              ) 

```

## merge demographic variables to items:
```{r}
df1 <- casp %>% 
  full_join(
    demo, by="mergeid"
  ) 
  #%>% 
  #dplyr::select(yrbirth, matches("^cC|^cA|^cP|^cS"))

# Storing the names of variables (items) as `manVars`:
manVars <- colnames(df1[,-c(1:2)])

# Storing the number of variables (items) as `nv`:
nv <- length(manVars)
```

## Missing Values
```{r missing}
# Define Missing Codes. Refer to the SHARE release guide for more detail:
missing_codes <- c(-1, -2, -3, -7, -9, -10, -11, -12, -14, -15, -16)

df2 <- df1 %>%
  mutate_all(~ifelse(. %in% missing_codes, NA, .))

# Check number of subjects with NAs on all CASP-12:
n_missings <- 
  sum(apply(df2[manVars], 1, function(row) all(is.na(row))))

df3 <- df2 %>% 
  filter(rowSums(is.na(.[manVars])) < length(manVars)) %>% 
# Remove missings on moderators gender and `age` (year of birth) and bfi items
  filter(complete.cases(yrbirth.x))
```

## Recode Items
```{r}
df4 <- df3 %>% 
  # Recode negative items of the Casp-12 questionnaire:
  mutate(
    cA1_1 = 5 - cA1_1,
    cP1_1 = 5 - cP1_1,
    cP2_1 = 5 - cP2_1,
    cP3_1 = 5 - cP3_1,
    cS1_1 = 5 - cS1_1,
    cS2_1 = 5 - cS2_1,
    cS3_1 = 5 - cS3_1,
    #
    cA1_2 = 5 - cA1_2,
    cP1_2 = 5 - cP1_2,
    cP2_2 = 5 - cP2_2,
    cP3_2 = 5 - cP3_2,
    cS1_2 = 5 - cS1_2,
    cS2_2 = 5 - cS2_2,
    cS3_2 = 5 - cS3_2,
    #
    cA1_4 = 5 - cA1_4,
    cP1_4 = 5 - cP1_4,
    cP2_4 = 5 - cP2_4,
    cP3_4 = 5 - cP3_4,
    cS1_4 = 5 - cS1_4,
    cS2_4 = 5 - cS2_4,
    cS3_4 = 5 - cS3_4,
    #
    cA1_5 = 5 - cA1_5,
    cP1_5 = 5 - cP1_5,
    cP2_5 = 5 - cP2_5,
    cP3_5 = 5 - cP3_5,
    cS1_5 = 5 - cS1_5,
    cS2_5 = 5 - cS2_5,
    cS3_5 = 5 - cS3_5,
    #
    cA1_6 = 5 - cA1_6,
    cP1_6 = 5 - cP1_6,
    cP2_6 = 5 - cP2_6,
    cP3_6 = 5 - cP3_6,
    cS1_6 = 5 - cS1_6,
    cS2_6 = 5 - cS2_6,
    cS3_6 = 5 - cS3_6,
    #
    cA1_7 = 5 - cA1_7,
    cP1_7 = 5 - cP1_7,
    cP2_7 = 5 - cP2_7,
    cP3_7 = 5 - cP3_7,
    cS1_7 = 5 - cS1_7,
    cS2_7 = 5 - cS2_7,
    cS3_7 = 5 - cS3_7,
    #
    cA1_8 = 5 - cA1_8,
    cP1_8 = 5 - cP1_8,
    cP2_8 = 5 - cP2_8,
    cP3_8 = 5 - cP3_8,
    cS1_8 = 5 - cS1_8,
    cS2_8 = 5 - cS2_8,
    cS3_8 = 5 - cS3_8,
  # Recode gender variable to `male` with 1 indicating male and 0 female:
    age = 2017 - yrbirth.x
  ) %>%  
  # Order variables:
  dplyr::select(age, everything())

```

```{r}
df4 <- df4 %>% 
        rename(
        "yrbirth" = "yrbirth.x",
        "gender"  = "gender.x" 
              ) 
```


```{r}
# Standardize all variables
#df_z <- df4 %>% 
# mutate_if(names(.) != "male", scale)
```

```{r}
df4_long <- pivot_longer(df4, cols = -c(1:4), 
             names_to = c('.value', 'wave'), 
             names_pattern = '(.*)(\\d+)')

```

```{r}
# Sanity check
write.csv2(cf_all, "cf_all.csv")
write.csv2(mh_all, "mh.csv")
write.csv2(casp_all, "casp.csv")
write.csv2(cfmh_all, "cfmh.csv")
write.csv2(df4, "df4.csv")

write.csv2(cf_long, "cf_long.csv")
write.csv2(mh_long, "mh_long.csv")
write.csv2(casp_long, "casp_long.csv")
write.csv2(cfmh_long, "cfmh_long.csv")
write.csv2(df4_long, "df4_long.csv")


```
